language: node_js
node_js:
    - 'stable'
cache: npm

install:
    - npm install

script:
    - npm run build

addons:
    ssh_known_hosts: 54.236.198.173

before_install:
    - openssl aes-256-cbc -K $encrypted_5f4afa0c33ba_key -iv $encrypted_5f4afa0c33ba_iv -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa

deploy:
    - provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist bitnami@54.236.198.173:/home/bitnami/stack/projects/spendy-backend/
      on:
          branch: main

after_success:
    - ssh bitnami@54.236.198.173 /home/bitnami/stack/projects/spendy-backend/redeploy.sh
